# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotenvify < Formula
  desc "Convert key-value pairs to environment variables"
  homepage "https://github.com/webb1es/dotenvify"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/webb1es/dotenvify/releases/download/v0.2.1/dotenvify_0.2.1_darwin_amd64.tar.gz"
      sha256 "5d6b5a75af1e63d2f24cd74fc1d5e9e6b6310096d7a28bab6d8822a7de16c88e"

      def install
        bin.install "dotenvify"
      end
    end
    on_arm do
      url "https://github.com/webb1es/dotenvify/releases/download/v0.2.1/dotenvify_0.2.1_darwin_arm64.tar.gz"
      sha256 "9658a9d963f1a4e0ec8811a4b99aea3f1bb220811c9be5efddb561e4a4f304ea"

      def install
        bin.install "dotenvify"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/webb1es/dotenvify/releases/download/v0.2.1/dotenvify_0.2.1_linux_amd64.tar.gz"
        sha256 "c6979ab9e4918d5668d5ba47af58676a2af2901af545775580ece4d9941f88c1"

        def install
          bin.install "dotenvify"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/webb1es/dotenvify/releases/download/v0.2.1/dotenvify_0.2.1_linux_arm64.tar.gz"
        sha256 "efdce39b943ef4bcbdce2e6cf2101a0e4818bc73dfb9ade9b6ca448df774f250"

        def install
          bin.install "dotenvify"
        end
      end
    end
  end

  test do
    system "#{bin}/dotenvify", "-h"
  end
end
