# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotenvify < Formula
  desc "Convert key-value pairs to environment variables"
  homepage "https://github.com/webb1es/dotenvify"
  version "0.3.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/webb1es/dotenvify/releases/download/v0.3.1/dotenvify_0.3.1_darwin_amd64.tar.gz"
      sha256 "b9f071d91892ca33649b99963ee1e684a1287d450f3580febca7badf9028dca8"

      def install
        bin.install "dotenvify"
      end
    end
    on_arm do
      url "https://github.com/webb1es/dotenvify/releases/download/v0.3.1/dotenvify_0.3.1_darwin_arm64.tar.gz"
      sha256 "8d00ac8b88d68e75a733de0eb56adbaf12add995aa9fc20413e500ba32a9e558"

      def install
        bin.install "dotenvify"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/webb1es/dotenvify/releases/download/v0.3.1/dotenvify_0.3.1_linux_amd64.tar.gz"
        sha256 "3deccdac3fa3bc2548416194d8b39aede90e5b58eab39ee8e7f0214fbce59b47"

        def install
          bin.install "dotenvify"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/webb1es/dotenvify/releases/download/v0.3.1/dotenvify_0.3.1_linux_arm64.tar.gz"
        sha256 "96b404fa454d4eba54fc19b9a7fdcb6a8287a5346cebfb9b251d7bd0659771b7"

        def install
          bin.install "dotenvify"
        end
      end
    end
  end

  test do
    system "#{bin}/dotenvify", "-h"
  end
end
