# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotenvify < Formula
  desc "Convert key-value pairs to environment variables"
  homepage "https://github.com/webb1es/dotenvify"
  version "0.1.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/webb1es/dotenvify/releases/download/v0.1.6/dotenvify_0.1.6_darwin_amd64.tar.gz"
      sha256 "cb8821cfe2efd74fbe73f4c64f8b4989e17f84ac32b17f3a046397800749fdee"

      def install
        bin.install "dotenvify"
      end
    end
    on_arm do
      url "https://github.com/webb1es/dotenvify/releases/download/v0.1.6/dotenvify_0.1.6_darwin_arm64.tar.gz"
      sha256 "4b1e71fa56addba4225e6558d13458fbbf99e21c03f356851a6c491cac53d07c"

      def install
        bin.install "dotenvify"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/webb1es/dotenvify/releases/download/v0.1.6/dotenvify_0.1.6_linux_amd64.tar.gz"
        sha256 "95667f0349b7f3baa90ae09f51156f8262799bdf3ee8da07b13e4994592ffbe1"

        def install
          bin.install "dotenvify"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/webb1es/dotenvify/releases/download/v0.1.6/dotenvify_0.1.6_linux_arm64.tar.gz"
        sha256 "2915f0b13fd19c5cdba0507e96581f9cdd065e5805dc5c86dbf06643ff311cec"

        def install
          bin.install "dotenvify"
        end
      end
    end
  end

  test do
    system "#{bin}/dotenvify", "-h"
  end
end
